##
## EPITECH PROJECT, 2022
## Makefile
## File description:
## makefile
##

all:
	$(MAKE) -C Snake
	$(MAKE) -C Pacman
	$(MAKE) -C Menu

clean:
	$(MAKE) clean -C Snake
	$(MAKE) clean -C Pacman
	$(MAKE) clean -C Menu

fclean: clean
	$(MAKE) fclean -C Snake
	$(MAKE) fclean -C Pacman
	$(MAKE) fclean -C Menu

debug:
	$(MAKE) debug -C Snake
	$(MAKE) debug -C Pacman
	$(MAKE) debug -C Menu

re:
	$(MAKE) re -C Snake
	$(MAKE) re -C Pacman
	$(MAKE) re -C Menu

.PHONY:	all clean fclean re
